### ISSUE TITLE
downloader has a race condition problem.

### ISSUE THREAD

**Issue by hhsprings** [kivy-garden/garden.mapview#18]
I wrote 'GPS tracking data player' like this:
```python
# -*- coding: utf-8 -*-
from datetime import datetime
from kivy.lang import Builder
from kivy.app import App
from kivy.properties import StringProperty
from kivy.uix.boxlayout import BoxLayout
from kivy.clock import Clock
from kivy.garden.mapview import MapView, MapMarker

Builder.load_string('''
<GardenMapviewDemo>:
    orientation: 'vertical'

    map: map

    MapView:
        id: map
        zoom: 17
''')

class GardenMapviewDemo(BoxLayout):

    def __init__(self):
        super(GardenMapviewDemo, self).__init__()

        self._data_all = []
        self._index = 0
        self._added_markers = []
        with open("location_all.csv") as fi:
            fi.readline()  # skip header
            for i, line in enumerate(fi.readlines()):
                self._data_all.append(
                    tuple(map(float, line.split(",")[:4])))

        self.update_view()

    def update_view(self, *arg, **kwarg):
        if self._added_markers:
            for m in self._added_markers:
                self.map.remove_marker(m)
            self._added_markers = []

        cur = self._data_all[self._index]

        self.map.center_on(cur[2], cur[1])
        m = MapMarker(lon=cur[1], lat=cur[2])
        self.map.add_marker(m)
        self._added_markers.append(m)

        if self._index < len(self._data_all) - 1:
            elapse = self._data_all[self._index + 1][0] - self._data_all[self._index][0]
            self._index += 1
            Clock.schedule_once(self.update_view, elapse / 2000) # very small elapse

class GardenMapviewDemoApp(App):
    def build(self):
        return GardenMapviewDemo()


if __name__ == '__main__':
    GardenMapviewDemoApp().run()
```
When the value to Clock.schedule_once is small, following error occurs:
```python
 Traceback (most recent call last):
   ...
   File "garden\mapview\mapview\downloader.py", line 108, in _check_executor
     callback(*args)
   File "garden\mapview\mapview\view.py", line 93, in set_source
     self.source = cache_fn
   File "kivy\graphics\instructions.pyx", line 360, in kivy.graphics.instructions.VertexInstruction.source.__set__ (kivy\graphics\instructions.c:7210)

   File "kivy\graphics\context_instructions.pyx", line 381, in kivy.graphics.context_instructions.BindTexture.source.__set__ (kivy\graphics\context_instructions.c:7367)
   File "core\image\__init__.py", line 512, in __init__
     self.filename = arg
   File "core\image\__init__.py", line 700, in _set_filename
     mipmap=self._mipmap, nocache=self._nocache)
   File "core\image\__init__.py", line 430, in load
     im = loader(filename, **kwargs)
   File "core\image\__init__.py", line 198, in __init__
     self._data = self.load(filename)
   File "core\image\img_sdl2.py", line 42, in load
     raise Exception('SDL2: Unable to load image')
 Exception: SDL2: Unable to load image
```
Actually, the file that img_sdl2#load says it isn't accessible exists and is accessible.

For example, following works fine (though is's very dirty):
```python
#... mapview/downloader.py
import os
import tempfile
#...
    def _load_tile(self, tile):
        if tile.state == "done":
            return
        cache_fn = tile.cache_fn
        if exists(cache_fn):
            return tile.set_source, (cache_fn, )
        tile_y = tile.map_source.get_row_count(tile.zoom) - tile.tile_y - 1
        uri = tile.map_source.url.format(z=tile.zoom, x=tile.tile_x, y=tile_y,
                              s=choice(tile.map_source.subdomains))
        #print "Download {}".format(uri)
        # --- FIX BEGIN
        res = requests.get(uri, timeout=5)
        if res.status_code == 404:
            return
        data = res.content
        # double-checking is also maybe ok.
        #if exists(cache_fn):
        #    # already exists. (maybe created by another future.)
        #    return tile.set_source, (cache_fn, )
        tf = tempfile.mkstemp()
        with os.fdopen(tf[0], "w") as fo:
            fo.write(data)
        try:
            os.rename(tf[1], cache_fn)
        except OSError as e:
            # already exists. (maybe created by another future.)
            #print(cache_fn, exists(cache_fn))
            os.unlink(tf[1])
        # --- FIX END
        #print "Downloaded {} bytes: {}".format(len(data), uri)
        return tile.set_source, (cache_fn, )

```
Maybe duplicate requests conflict each other, I think.

**Comment by tito** [comment]
You're right, i'll rework the downloader to make it more efficient and prevent duplicates.

**Comment by mebloscian** [comment]
Just used solution posted above and it seems like the problem is gone. I've also lowered MAX_WORKERS in Downloader class to 3. Tiles loads a bit slower, it's way more stable though.
