### ISSUE TITLE
Adding MapView to Kivy project

### ISSUE THREAD

**Issue by ehsanaerabi** [kivy-garden/garden.mapview#30]
I see following error whenever I add MapView to my code: 

### [INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-12-21_18.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "project.py", line 130, in <module>
     WidgetsApp().run()
   File "/usr/local/lib/python2.7/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 90, in mainloop
     self._mainloop()
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 85, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 339, in idle
     Clock.tick()
   File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 368, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7740)
   File "kivy/_clock.pyx", line 398, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7617)
   File "kivy/_clock.pyx", line 396, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7538)
   File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3530)
   File "/root/.kivy/garden/garden.mapview/mapview/downloader.py", line 87, in _check_executor
     callback(*args)
   File "/root/.kivy/garden/garden.mapview/mapview/view.py", line 102, in set_source
     self.source = cache_fn
   File "kivy/graphics/instructions.pyx", line 362, in kivy.graphics.instructions.VertexInstruction.source.__set__ (kivy/graphics/instructions.c:9032)
   File "kivy/graphics/context_instructions.pyx", line 383, in kivy.graphics.context_instructions.BindTexture.source.__set__ (kivy/graphics/context_instructions.c:8872)
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 538, in __init__
     self.filename = arg
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 734, in _set_filename
     mipmap=self._mipmap, nocache=self._nocache)
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 435, in load
     im = loader(filename, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/__init__.py", line 201, in __init__
     self._data = self.load(filename)
   File "/usr/local/lib/python2.7/dist-packages/kivy/core/image/img_pygame.py", line 85, in load
     (filename, im.fmt))
 AttributeError: 'pygame.Surface' object has no attribute 'fmt'

**Comment by tito** [comment]
Unfortunately, it's not an issue with mapview, but more with Kivy itself. Plus, pygame is now out of the picture in Kivy, SDL2 is used on all platforms!
