### ISSUE TITLE
GeoJsonMapLayer crashed during simple_geojson.py

### ISSUE THREAD

**Issue by sadov** [kivy-garden/garden.mapview#37]
$ python simple_geojson.py
....
 Traceback (most recent call last):
   File "simple_geojson.py", line 51, in <module>
     runTouchApp(view)
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 525, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 290, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/data/home/user/.kivy/garden/garden.mapview/mapview/downloader.py", line 102, in _check_executor
     callback(*args)
   File "/data/home/user/.kivy/garden/garden.mapview/mapview/geojson.py", line 304, in _load_geojson_url
     self.geojson = r.json()
   File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4818)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5389)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:6070)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12854)
   File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:12051)
   File "/data/home/user/.kivy/garden/garden.mapview/mapview/geojson.py", line 290, in on_geojson
     self.canvas_line.clear()
 AttributeError: 'GeoJsonMapLayer' object has no attribute 'canvas_line'

**Comment by fitoprincipe** [comment]
same issue here

**Comment by fitoprincipe** [comment]
solved commenting line 290 and 291 of geojson.py

**Comment by mcroni** [comment]
this doesnt solve the problem, it even prevents the downloader from doing its job
