### ISSUE TITLE
Syntax error in garden.mapview\mapview\__init__.py

### ISSUE THREAD

**Issue by vipercortex** [kivy-garden/garden.mapview#51]
The following test code on Python 3.6.5 Anaconda:

from kivy.garden.mapview import MapView
from kivy.app import App
class MapViewApp(App):
    def build(self):
        mapview = MapView(zoom=11, lat=50.6394, lon=3.057)
        return mapview
MapViewApp().run()

generates the following error:

Traceback (most recent call last):
   File "test_mapview.py", line 2, in <module>
     from kivy.garden.mapview import MapView
   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
   File "C:\Anaconda3\lib\site-packages\kivy\garden\__init__.py", line 100, in load_module
     return self._load_module(fullname, moddir)
   File "C:\Anaconda3\lib\site-packages\kivy\garden\__init__.py", line 104, in _load_module
     ('', '', imp.PKG_DIRECTORY))
   File "C:\Anaconda3\lib\imp.py", line 245, in load_module
     return load_package(name, filename)
   File "C:\Anaconda3\lib\imp.py", line 217, in load_package
     return _load(spec)
   File "C:\Users\jmangelschots\.kivy\garden\garden.mapview\__init__.py", line 3, in <module>
     from .mapview import *
   File "C:\Users\jmangelschots\.kivy\garden\garden.mapview\mapview\__init__.py", line 31, in <module>
     from mapview.view import MapView, MapMarker, MapLayer, MarkerMapLayer, \
   File "C:\Users\jmangelschots\.kivy\garden\garden.mapview\mapview\view.py", line 209
     lambda (i, m): m.lat < marker.lat,

 SyntaxError: invalid syntax

**Comment by ghost** [comment]
I have the same problem!

    >>> import kivy.garden.mapview
    [INFO   ] [Logger      ] Record log in /home/iku/.kivy/logs/kivy_18-08-20_46.txt
    [INFO   ] [Kivy        ] v1.10.1
    [INFO   ] [Python      ] v3.6.5 (default, Apr  1 2018, 05:46:30) 
    [GCC 7.3.0]
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
       File "<frozen importlib._bootstrap>", line 971, in _find_and_load
       File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
       File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
       File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
       File "/home/iku/.virtualenvs/k36/lib/python3.6/site-packages/kivy/garden/__init__.py", line 100, in load_module
         return self._load_module(fullname, moddir)
       File "/home/iku/.virtualenvs/k36/lib/python3.6/site-packages/kivy/garden/__init__.py", line 104, in _load_module
     ('', '', imp.PKG_DIRECTORY))
       File "/home/iku/.virtualenvs/k36/lib/python3.6/imp.py", line 245, in load_module
         return load_package(name, filename)
       File "/home/iku/.virtualenvs/k36/lib/python3.6/imp.py", line 217, in load_package
         return _load(spec)
       File "/home/iku/.kivy/garden/garden.mapview/__init__.py", line 3, in <module>
         from .mapview import *
       File "/home/iku/.kivy/garden/garden.mapview/mapview/__init__.py", line 31, in <module>
         from mapview.view import MapView, MapMarker, MapLayer, MarkerMapLayer, \
       File "/home/iku/.kivy/garden/garden.mapview/mapview/view.py", line 209
         lambda (i, m): m.lat < marker.lat,
                ^
     SyntaxError: invalid syntax

**Comment by AndreMiras** [comment]
Fixed in https://github.com/kivy-garden/garden.mapview/pull/66
