### ISSUE TITLE
Crash when MarkerMapLayer without Marker

### ISSUE THREAD

**Issue by AndreMiras** [kivy-garden/garden.mapview#6]
When adding a MarkerMapLayer with no marker to a MapView, the application crashes.
Even though it may not be relevant to add a MarkerMapLayer without Marker, we also get the issue when adding makers then removing them all.

Sample application:

``` python
from kivy.base import runTouchApp
from kivy.garden.mapview import MapView, MarkerMapLayer

mapview = MapView()
# empty MarkerMapLayer, layer causes ValueError exception
# ValueError: max() arg is an empty sequence
mapview.add_layer(MarkerMapLayer())
runTouchApp(mapview)
```

Stacktrace:

```
[INFO              ] [Logger      ] Record log in /home/andre/.kivy/logs/kivy_15-07-31_46.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v2.7.9 (default, Feb  2 2015, 23:47:54) 
[GCC 4.8.3]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
libpng warning: iCCP: known incorrect sRGB profile
[INFO              ] [GL          ] OpenGL version <3.0 Mesa 10.2.8>
[INFO              ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO              ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ivybridge Mobile >
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <1.30>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: pygame
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO              ] [MTD         ] Read event from </dev/input/event1>
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "tests/marker_map_layer_crash.py", line 8, in <module>
     runTouchApp(mapview)
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 398, in mainloop
     self._mainloop()
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop
     EventLoop.idle()
     Exception in thread Thread-1:
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
 Traceback (most recent call last):
     Clock.tick()
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/clock.py", line 483, in tick
     self._process_events()
   File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/clock.py", line 615, in _process_events
     self.run()
     event.tick(self._last_tick, remove)
   File "/usr/lib64/python2.7/threading.py", line 763, in run
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/clock.py", line 374, in tick
     self.__target(*self.__args, **self.__kwargs)
     ret = callback(self._dt)
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/input/providers/mtdev.py", line 197, in _thread_run
   File "/home/andre/.kivy/garden/garden.mapview/mapview/view.py", line 692, in do_update
     _device = Device(_fn)
     layer.reposition()
   File "/home/andre/Progz/guyps/lib/python2.7/site-packages/kivy/lib/mtdev.py", line 131, in __init__
   File "/home/andre/.kivy/garden/garden.mapview/mapview/view.py", line 209, in reposition
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
     margin = max((max(marker.size) for marker in markers))
 OSError: [Errno 13] Permission denied: '/dev/input/event1'
 ValueError: max() arg is an empty sequence
```

Additional info:
- Python 2.7.9
- Kivy==1.9.0
- garden.mapview master (currently 97257ac8c7187051a7cd652bc7d2ef04fe849dad) installed with `garden install mapview`

**Comment by tamaradjerdj** [comment]
A trick is to add a marker whose source is a transparent .png. It should be added apart from other markers (stored in a different variable), so that when you remove the visible markers, the transparent one stays and the MarkerMapLayer never gets empty. 

I'm curious about other solutions for avoiding this error.

**Comment by zoltan-fedor** [comment]
I was just faced with the same problem and adding a transparent .png worked perfectly! Thanks!
