### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by asm201** [kivy-garden/garden.mapview#84]
I was trying to see the exemples documents but i receive this error:
`Traceback (most recent call last):
   File "C:/Users/André/AppData/Local/Programs/Python/Python37/Lib/site-packages/kivy/garden/garden.mapview/examples/clustered_geojson.py", line 16, in <module>
     layer = GeoJsonMapLayer(source=source)
   File "C:\Users\André\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\garden\garden.mapview\mapview\geojson.py", line 198, in __init__
     super(GeoJsonMapLayer, self).__init__(**kwargs)
   File "C:\Users\André\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 350, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 262, in kivy._event.EventDispatcher.__init__
   File "kivy\properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "C:\Users\André\AppData\Local\Programs\Python\Python37\Lib\site-packages\kivy\garden\garden.mapview\mapview\geojson.py", line 299, in on_source
     geojson = json.load(fd)
   File "C:\Users\André\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
   File "C:\Users\André\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
     return _default_decoder.decode(s)
   File "C:\Users\André\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "C:\Users\André\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

the code i was trying to run was this one:

```
from kivy.base import runTouchApp
import sys

if __name__ == '__main__' and __package__ is None:
    from os import path
    sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))

from mapview import MapView, MapMarker
from mapview.geojson import GeoJsonMapLayer
from mapview.utils import haversine, get_zoom_for_radius

if len(sys.argv) > 1:
    source = sys.argv[1]
else:
    source = "https://storage.googleapis.com/maps-devrel/google.json"

options = {}
layer = GeoJsonMapLayer(source=source)

if layer.geojson:
    # try to auto center the map on the source
    lon, lat = layer.center
    options["lon"] = lon
    options["lat"] = lat
    min_lon, max_lon, min_lat, max_lat = layer.bounds
    radius = haversine(min_lon, min_lat, max_lon, max_lat)
    zoom = get_zoom_for_radius(radius, lat)
    options["zoom"] = zoom

view = MapView(**options)
view.add_layer(layer)

if layer.geojson:
    # create marker if they exists
    count = 0

    def create_marker(feature):
        global count
        geometry = feature["geometry"]
        if geometry["type"] != "Point":
            return
        lon, lat = geometry["coordinates"]
        marker = MapMarker(lon=lon, lat=lat)
        view.add_marker(marker)
        count += 1

    layer.traverse_feature(create_marker)
    if count:
        print("Loaded {} markers".format(count))

runTouchApp(view)
```

**Comment by AndreMiras** [comment]
Hi @asm201, thanks for the bug report!
Ideally you should make a more minimalist example.
More specifically I'd like you to make this part more clear so we don't have to guess what you passed in your `sys.argv`:
```python
if len(sys.argv) > 1:
    source = sys.argv[1]
else:
    source = "https://storage.googleapis.com/maps-devrel/google.json"
```
Also since this is already crashing on this line:
```
layer = GeoJsonMapLayer(source=source)
```
Please cut the rest to provide the most minimalist and deterministic example so we can help debugging.
Deterministic would also mean not relying on a remote location content that could change any time, hence please share (attach) the actual JSON file content you've tried with rather than the potential URL of it (https://storage.googleapis.com/maps-devrel/google.json).
I hope that makes sense

**Comment by asm201** [comment]
sorry i forgot to mention that this code is from exemple folder that comes with the garden.mapview, i also don't know what passed in `sys.argv`

**Comment by AndreMiras** [comment]
Clear thank you. This repo needs some love anyway. I'll try to look over the weekend
